// Put constants here if you want!
export const sports = ["ARCHERY", "ARTISTIC SWIMMING", "ATHLETICS,BADMINTON", "BASKETBALL", "BEACH VOLLEYBALL", 
  "BOXING", "CANOE SLALOM", "CANOE SPRINT", "CYCLING BMX", "CYCLING MOUNTAIN BIKE", 
  "CYCLING ROAD", "CYCLING TRACK", "DIVING", "EQUESTRIAN / DRESSAGE", "EQUESTRIAN EVENTING",
  "EQUESTRIAN JUMPING", "FENCING", "FOOTBALL", "GOLF", "GYMNASTICS ARTISTIC", "GYMNASTICS RHYTHMIC",
  "HANDBALL", "HOCKEY", "JUDO", "MARATHON SWIMMING", "MODERN PENTATHLON", "ROWING", "RUGBY", "SAILING",
  "SHOOTING", "SWIMMING", "TABLE TENNIS", "TAEKWONDO", "TENNIS", "TRAMPOLINE", "TRIATHLON",
  "VOLLEYBALL", "WATER POLO", "WEIGHTLIFTING", "WRESTLING FREESTYLE", "WRESTLING GRECO-ROMAN",
  "ALPINE SKIING", "BIATHLON", "BOBSLEIGH", "CROSS COUNTRY SKIING", "CURLING", "FIGURE SKATING",
  "FREESTYLE SKIING", "ICE HOCKEY", "LUGE", "NORDIC COMBINED", "SHORT TRACK", "SKELETON",
  "SKI JUMPING", "SNOWBOARD", "SPEED SKATING"]